server:
  port: 8081

spring:
  application:
    name: artemis

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@jhipster-registry:8761/eureka/
