services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
  artemis-1:
    build:
      context: ./artemis
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=text,quiz
    networks:
      - app-network
  artemis-2:
    build:
      context: ./artemis
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=quiz
    networks:
      - app-network
  jhipster-registry:
    image: jhipster/jhipster-registry
    container_name: jhipster-registry
    ports:
      - "8761:8761"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
