services:
  api-gateway:
    build:
      context: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
  artemis:
    build:
      context: .
      dockerfile: artemis/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
  jhipster-registry:
    image: jhipster/jhipster-registry
    container_name: jhipster-registry
    ports:
      - "8761:8761"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
