spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: artemis
          uri: lb://ARTEMIS
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true
      httpclient:
        pool:
          max-connections: 500
          acquire-timeout: 1000
        # same value as nginx proxy timeout in artemis config. Debatable, if such a timeout really makes sense.
        # In particular, when having high load, one should DECREASE the timeout to a reasonable value
        # to allow "recovering" from long-running requests
        response-timeout: 900s

custom-routing:
  profileMetadataKey: profile # the name of the property that holds a comma-separated list of active profiles
  profile-mappings:
    # Defines which active profile an instance has to receive requests for /api/<map-value>/**
    # nonDefaultProfilesByPrefix:
      # atlas: atlas
    # Defines which active profile an instance has to have to receive all requests for path that did not match any prefix
    defaultProfile: core

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-"http://admin:admin@localhost:8761/eureka/"}
    enabled: true
  instance:
    preferIpAddress: true
    appname: API-Gateway
management:
  endpoints:
    web:
      exposure:
        include: "gateway"
  # uncomment in case you want to access information regarding the gateway (routes) under /actuator/gateway
  # otherwise, the endpoint is NOT exposed at all
  # endpoint:
    # gateway:
      # access: unrestricted
