spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: artemis
          uri: lb://ARTEMIS
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true

custom-routing:
  profileMetadataKey: profile # the name of the property that holds a comma-separated list of active profiles
  profile-mappings:
    # Defines which active profile an instance has to receive requests for /api/<map-value>/**
    nonDefaultProfilesByPrefix:
      atlas: atlas
      text: text
    # Defines which active profile an instance has to have to receive all requests for path that did not match any prefix
    defaultProfile: core

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-"http://admin:admin@localhost:8761/eureka/"}
    enabled: true
  instance:
    preferIpAddress: true
    appname: API-Gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.cloud.loadbalancer: DEBUG
