spring:
  application:
    name: main-service
  cloud:
    consul:
      host: localhost # Consul agent host
      port: 8500      # Consul agent port
      # discovery:
        # enabled: true # Enable service discovery
