name: nemesis
services:
  influxdb:
    image: influxdb:2.7.6
    volumes:
      - influx-etc:/etc/influxdb2
      - influx-lib:/var/lib/influxdb2
      - /var/lib/rbg-cert/2024-12-03/nemesis.ase.cit.tum.de.cert.pem:/etc/ssl/cert.pem:ro
      - /var/lib/rbg-cert/2024-12-03/nemesis.ase.cit.tum.de.privkey.pem:/etc/ssl/privkey.pem:ro
    ports:
      - "8443:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      INFLUXDB_HTTP_HTTPS_ENABLED: true
      INFLUXD_TLS_CERT: /etc/ssl/cert.pem
      INFLUXD_TLS_KEY: /etc/ssl/privkey.pem

volumes:
  influx-etc:
  influx-lib: